-- Snowflake stream + task orchestration example for incremental finance processing.

CREATE OR REPLACE STREAM FINANCE_AI_DEMO.BRONZE.BILLING_EVENTS_STREAM
ON TABLE FINANCE_AI_DEMO.BRONZE.BILLING_EVENTS
APPEND_ONLY = TRUE;

CREATE OR REPLACE TASK FINANCE_AI_DEMO.AI.TASK_REFRESH_FINANCE_MARTS
WAREHOUSE = ANALYTICS_WH
SCHEDULE = 'USING CRON 0 * * * * UTC'
WHEN SYSTEM$STREAM_HAS_DATA('FINANCE_AI_DEMO.BRONZE.BILLING_EVENTS_STREAM')
AS
BEGIN
    -- Touch dynamic tables through a deterministic refresh query.
    SELECT COUNT(*) FROM FINANCE_AI_DEMO.GOLD.MART_FINANCE_KPIS;
    SELECT COUNT(*) FROM FINANCE_AI_DEMO.GOLD.MART_FINANCE_VARIANCE_BRIDGE;
    SELECT COUNT(*) FROM FINANCE_AI_DEMO.GOLD.MART_ACCOUNT_RISK;
END;

CREATE OR REPLACE TASK FINANCE_AI_DEMO.AI.TASK_BUILD_EXEC_SUMMARY
WAREHOUSE = ANALYTICS_WH
AFTER FINANCE_AI_DEMO.AI.TASK_REFRESH_FINANCE_MARTS
AS
INSERT INTO FINANCE_AI_DEMO.AI.FINANCE_EXEC_SUMMARY_LOG
SELECT
    CURRENT_TIMESTAMP() AS GENERATED_AT,
    MONTH,
    ARR,
    NRR_PCT,
    DSO_DAYS,
    OPEN_AR,
    ARR_VARIANCE,
    CASH_VARIANCE,
    AR_VARIANCE
FROM FINANCE_AI_DEMO.GOLD.MART_FINANCE_VARIANCE_BRIDGE
QUALIFY MONTH = MAX(MONTH) OVER ();

ALTER TASK FINANCE_AI_DEMO.AI.TASK_REFRESH_FINANCE_MARTS RESUME;
ALTER TASK FINANCE_AI_DEMO.AI.TASK_BUILD_EXEC_SUMMARY RESUME;