-- Snowflake-native object definitions that mirror the local demo schema.

CREATE DATABASE IF NOT EXISTS FINANCE_AI_DEMO;
CREATE SCHEMA IF NOT EXISTS FINANCE_AI_DEMO.BRONZE;
CREATE SCHEMA IF NOT EXISTS FINANCE_AI_DEMO.SILVER;
CREATE SCHEMA IF NOT EXISTS FINANCE_AI_DEMO.GOLD;
CREATE SCHEMA IF NOT EXISTS FINANCE_AI_DEMO.AI;

CREATE OR REPLACE TABLE FINANCE_AI_DEMO.BRONZE.BILLING_EVENTS (
    ACCOUNT_ID STRING,
    ACCOUNT_NAME STRING,
    MONTH DATE,
    REGION STRING,
    SEGMENT STRING,
    PLAN_TIER STRING,
    RENEWAL_DATE DATE,
    SEATS NUMBER,
    MRR NUMBER(18,2),
    BILLED_AMOUNT NUMBER(18,2),
    COLLECTED_AMOUNT NUMBER(18,2),
    DAYS_LATE NUMBER,
    ADOPTION_SCORE NUMBER(10,2),
    SUPPORT_TICKETS NUMBER,
    EXPANSION_AMOUNT NUMBER(18,2),
    CONTRACTION_AMOUNT NUMBER(18,2),
    CHURN_FLAG NUMBER
);

CREATE OR REPLACE TABLE FINANCE_AI_DEMO.BRONZE.FORECAST_PLAN (
    MONTH DATE,
    FORECAST_ARR NUMBER(18,2),
    FORECAST_COLLECTED_CASH NUMBER(18,2),
    FORECAST_OPEN_AR NUMBER(18,2),
    FORECAST_NRR_PCT NUMBER(10,2)
);

CREATE OR REPLACE VIEW FINANCE_AI_DEMO.SILVER.SILVER_ACCOUNT_MONTHLY AS
WITH base AS (
    SELECT
        ACCOUNT_ID,
        ACCOUNT_NAME,
        MONTH,
        REGION,
        SEGMENT,
        PLAN_TIER,
        RENEWAL_DATE,
        SEATS,
        MRR,
        BILLED_AMOUNT,
        COLLECTED_AMOUNT,
        BILLED_AMOUNT - COLLECTED_AMOUNT AS OPEN_AR,
        DAYS_LATE,
        ADOPTION_SCORE,
        SUPPORT_TICKETS,
        EXPANSION_AMOUNT,
        CONTRACTION_AMOUNT,
        CHURN_FLAG,
        LAG(MRR) OVER (PARTITION BY ACCOUNT_ID ORDER BY MONTH) AS PRIOR_MRR
    FROM FINANCE_AI_DEMO.BRONZE.BILLING_EVENTS
)
SELECT
    *,
    IFF(RENEWAL_DATE <= DATEADD(DAY, 90, MONTH), 1, 0) AS RENEWAL_IN_90_DAYS
FROM base;

CREATE OR REPLACE DYNAMIC TABLE FINANCE_AI_DEMO.GOLD.MART_FINANCE_KPIS
TARGET_LAG = '1 HOUR'
WAREHOUSE = ANALYTICS_WH
AS
WITH monthly AS (
    SELECT
        MONTH,
        SUM(MRR) * 12.0 AS ARR,
        SUM(BILLED_AMOUNT) AS BILLED_REVENUE,
        SUM(COLLECTED_AMOUNT) AS COLLECTED_CASH,
        SUM(OPEN_AR) AS OPEN_AR,
        SUM(PRIOR_MRR) AS PRIOR_PERIOD_MRR,
        SUM(MRR) AS CURRENT_PERIOD_MRR,
        SUM(EXPANSION_AMOUNT) AS EXPANSION_REVENUE,
        SUM(CONTRACTION_AMOUNT) AS CONTRACTION_REVENUE,
        SUM(IFF(CHURN_FLAG = 1, PRIOR_MRR, 0)) AS CHURNED_REVENUE,
        SUM(CHURN_FLAG) AS CHURNED_ACCOUNTS,
        COUNT(DISTINCT ACCOUNT_ID) AS ACTIVE_ACCOUNTS
    FROM FINANCE_AI_DEMO.SILVER.SILVER_ACCOUNT_MONTHLY
    GROUP BY MONTH
)
SELECT
    MONTH,
    ARR,
    BILLED_REVENUE,
    COLLECTED_CASH,
    OPEN_AR,
    IFF(BILLED_REVENUE = 0, 0, (OPEN_AR / BILLED_REVENUE) * 30) AS DSO_DAYS,
    IFF(PRIOR_PERIOD_MRR = 0, 100, ((PRIOR_PERIOD_MRR - CHURNED_REVENUE - CONTRACTION_REVENUE + EXPANSION_REVENUE) / PRIOR_PERIOD_MRR) * 100) AS NRR_PCT,
    IFF(PRIOR_PERIOD_MRR = 0, 100, ((PRIOR_PERIOD_MRR - CHURNED_REVENUE - CONTRACTION_REVENUE) / PRIOR_PERIOD_MRR) * 100) AS GROSS_REVENUE_RETENTION_PCT,
    IFF(ACTIVE_ACCOUNTS = 0, 0, CHURNED_ACCOUNTS * 100.0 / ACTIVE_ACCOUNTS) AS LOGO_CHURN_PCT,
    ACTIVE_ACCOUNTS,
    CHURNED_ACCOUNTS
FROM monthly;

CREATE OR REPLACE DYNAMIC TABLE FINANCE_AI_DEMO.GOLD.MART_FINANCE_VARIANCE_BRIDGE
TARGET_LAG = '1 HOUR'
WAREHOUSE = ANALYTICS_WH
AS
SELECT
    k.MONTH,
    k.ARR,
    f.FORECAST_ARR,
    k.ARR - f.FORECAST_ARR AS ARR_VARIANCE,
    k.COLLECTED_CASH,
    f.FORECAST_COLLECTED_CASH,
    k.COLLECTED_CASH - f.FORECAST_COLLECTED_CASH AS CASH_VARIANCE,
    k.OPEN_AR,
    f.FORECAST_OPEN_AR,
    k.OPEN_AR - f.FORECAST_OPEN_AR AS AR_VARIANCE,
    k.NRR_PCT,
    f.FORECAST_NRR_PCT,
    k.NRR_PCT - f.FORECAST_NRR_PCT AS NRR_VARIANCE_PCT,
    k.LOGO_CHURN_PCT,
    k.GROSS_REVENUE_RETENTION_PCT
FROM FINANCE_AI_DEMO.GOLD.MART_FINANCE_KPIS k
LEFT JOIN FINANCE_AI_DEMO.BRONZE.FORECAST_PLAN f
    ON k.MONTH = f.MONTH;

CREATE OR REPLACE DYNAMIC TABLE FINANCE_AI_DEMO.GOLD.MART_ACCOUNT_RISK
TARGET_LAG = '1 HOUR'
WAREHOUSE = ANALYTICS_WH
AS
SELECT
    ACCOUNT_ID,
    ACCOUNT_NAME,
    REGION,
    SEGMENT,
    PLAN_TIER,
    MONTH,
    RENEWAL_DATE,
    OPEN_AR,
    MRR,
    ADOPTION_SCORE,
    DAYS_LATE,
    SUPPORT_TICKETS,
    RENEWAL_IN_90_DAYS,
    (
        IFF(OPEN_AR > 5000, 35, OPEN_AR / 180) +
        IFF(ADOPTION_SCORE < 55, 25, IFF(ADOPTION_SCORE < 70, 12, 0)) +
        IFF(DAYS_LATE >= 20, 20, IFF(DAYS_LATE >= 10, 10, 0)) +
        IFF(SUPPORT_TICKETS >= 4, 10, SUPPORT_TICKETS * 2) +
        IFF(RENEWAL_IN_90_DAYS = 1, 15, 0)
    ) AS RISK_SCORE
FROM FINANCE_AI_DEMO.SILVER.SILVER_ACCOUNT_MONTHLY
QUALIFY MONTH = MAX(MONTH) OVER ();